version: "3.8"
services:
  mongodb:
    image: 'mongo'
    container_name: mongodb

    volumes:
      - data:/data/db
    # enviroment:
    #   MONGO_INITDB_ROOT_USERNAME : xiu 
    #   MONGO_INITDB_ROOT_PASSWORD : secret 
    # -MONGO_INITDB_ROOT_PASSWORD =secret
    env_file:
      - ./env/mongo.env
    networks:
      - goals-net

  backend:
    build: ./backend
    container_name: backend
    # context: ./backend
    # dockerfile: Dockerfile
    # args:
    #   some-arg: 1
    ports:
      - '80:80'
    networks:
      - goals-net
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
    
  frontend:
    build : ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - goals-net
    stdin_open: true
    tty: true
    

volumes:
  data:
  logs:

networks:
  goals-net:
